language: go

go:
  - 1.16.x
  - 1.17.x

install:
  - export PATH=${PATH}:${HOME}/gopath/bin
  - go install -v golang.org/x/lint/golint@latest

before_script:
  - go vet ./...
  - golint .

script:
  - go test -v ./...
  - go test -v -race ./...
